### ISSUE TITLE
Unable to use SDK in Vercel serverless environment due to proxy-agent dependency.

### ISSUE THREAD

**Issue by andrusch** [box/box-typescript-sdk-gen#310]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

I've built a NextJS app and have included the Box SDK within some API routes. These routes work locally and also from a clean GitPod environment. When the NextJS route is deployed to Vercel, I receive the following error when trying to execute any of the API routes that include Box SDK. 

### Steps to Reproduce
1. Create a NextJS starter project and place the lines of code below in an API route folder. This example is for demonstratable purposes only. [Get Started with NextJS](https://nextjs.org/docs/getting-started/installation)
2. 
```javascript
import {
  BOX_CLIENT_ID,
  BOX_CLIENT_SECRET,
  BOX_CONTRACT_TEMPLATE_ID,
  BOX_ENTERPRISE_ID,
  BOX_USER_ID,
} from '@/constants'
import { BoxCcgAuth } from 'box-typescript-sdk-gen'

export async function GET(
  req: NextRequest
) {
  try {
    const authClient = new BoxCcgAuth({ config: this._config });
    const tokenResponse = await authClient.withUserSubject(BOX_USER_ID as string).retrieveToken()
    return NextResponse.json({ success: true }, { status: 200 })
  } catch (e) { return NextResponse.json({ success: false }, { status: 400 }) }
}

```
3. Deploy to [Vercel.com](https://vercel.com/) with the free plan
4. Call the API from Postman 

### Expected Behavior

You should receive a 200

### Error Message, Including Stack Trace

```
⨯ Error: Cannot find module 'proxy-agent'
Require stack:
- /var/task/.next/server/chunks/295.js
- /var/task/.next/server/webpack-runtime.js
- /var/task/.next/server/instrumentation.js
- /var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js
- /var/task/___next_launcher.cjs
- /opt/rust/nodejs.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at /var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:25613
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at /opt/rust/nodejs.js:1:11604
    at Function.or (/opt/rust/nodejs.js:1:11978)
    at e.<computed>.te._load (/opt/rust/nodejs.js:1:11574)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at b.require (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:25829)
    at a (/opt/rust/bytecode.js:1:1075)
    at createAgent (/var/task/.next/server/chunks/295.js:1:37998) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/.next/server/chunks/295.js',
    '/var/task/.next/server/webpack-runtime.js',
    '/var/task/.next/server/instrumentation.js',
    '/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js',
    '/var/task/___next_launcher.cjs',
    '/opt/rust/nodejs.js'
  ]
}
```

### Versions Used

Typescript SDK: "box-typescript-sdk-gen": "^1.1.0"
Platform: Vercel
Node.js (if applicable): 20x
"typescript": "^5.3.3"

[sdk-docs]: https://github.com/box/box-typescript-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-typescript-sdk-gen/search?type=Issues

**Comment by congminh1254** [comment]
Hi @andrusch 

Can you take a look at [this comment](https://github.com/box/box-typescript-sdk-gen/issues/213#issuecomment-2285387965)

Please let me know if it works for your case.

Bests,
Minh

**Comment by andrusch** [comment]
Hey @congminh1254 

Yep, this resolved the issue. Apologies for not finding that ahead of opening this.

Best,
Charlie
