### ISSUE TITLE
Error searching for the file: Can't deserialize SearchResultsOrSearchResultsWithSharedLinks

### ISSUE THREAD

**Issue by KenZync** [box/box-typescript-sdk-gen#32]
### Description of the Issue

I cant Search

### Steps to Reproduce

`  let fileName='o2ma1000.ojn'
  try {
    const fileSearch = await client.search.getSearch({query:fileName});

  } catch (error) {
    console.error("Error searching for the file:", error);
    return null;
  }
`
Error searching for the file: Can't deserialize SearchResultsOrSearchResultsWithSharedLinks

**Comment by mwwoda** [comment]
It looks like problem on the SDK side. We'll look into it. I'll let you know of in case of any updates.

**Comment by mhagmajer** [comment]
It's a spec problem. Will be solved by https://github.com/box/box-openapi/pull/357

**Comment by mhagmajer** [comment]
Should work now 👍
