### ISSUE TITLE
Can't refresh token

### ISSUE THREAD

**Issue by gdelory** [box/box-typescript-sdk-gen#34]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

I'm opening this bug issue following our discussion in the forum ([comment here](https://forum.box.com/t/has-anyone-tried-the-new-typescript-sdk/921/10?u=gdelory)), since this place seems more appropriate 😉 I'm still not sure if this is an assistance request (I'm doing something wrong) or a bug so I chose the question template.

The issue is that with the new TS SDK, when using the OAuth authentication and I;m trying to explicitly refresh the `AccessToken` I got through a OAuth loop (note that the OAuth loop was done with the legacy box-node-sdk because that's what we have right now on our live app handling the flow), it fails with the following error:

```
/home/gui/<concealed by 1Password>/node_modules/box-typescript-sdk-gen/lib/fetch.js:5
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
                                                         ^
Error: Request failed, status code 400: Bad Request

      {
  "error": "invalid_grant",
  "error_description": "Invalid refresh token"
}
    at /home/gui/<concealed by 1Password>/node_modules/box-typescript-sdk-gen/src/fetch.ts:199:11
    at Generator.next (<anonymous>)
    at fulfilled (/home/gui/<concealed by 1Password>/node_modules/box-typescript-sdk-gen/lib/fetch.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I understand that it seems to say that the refresh token is invalid, but the issue is that I received it as result of the OAuth flow a few minutes before trying, so that seems unlikely that it is already expired.

Here is my test code I'm using to get the client and call the refresh. Note that the token for this user is already in the DB, since I just did the OAuth loop with our live app

```
import { get, insert, MainDB, initDBConnectionSync } from '@dcs/common-tooling/lib/databases/DBUtilsServer'
import config from '../config'
import SecretUtils from './SecretUtils'
import { Client } from 'box-typescript-sdk-gen/lib/client.generated.js'
import { OAuth } from 'box-typescript-sdk-gen/lib/oauth'
import { TokenStorage } from 'box-typescript-sdk-gen/lib/tokenStorage'
import { AccessToken } from 'box-typescript-sdk-gen/lib/schemas.generated'
import { User } from '@dcs/common-tooling/lib/databases/DocumentTypes'

class WfmTokenStorage implements TokenStorage {
  
  private db: MainDB
  private userId: string

  constructor(db: MainDB, userId: string) {
    this.db = db
    this.userId = userId
  }

  async store(token: AccessToken): Promise<void> {
    await setToken(this.db, this.userId, token)
  }
  async get(): Promise<AccessToken | undefined> {
    return await getToken(this.db, this.userId) as AccessToken | undefined
  }
  clear(): void {
  }
}
 
export async function setToken(db: MainDB, userId: string, token: AccessToken) {
  const user = await get(db, userId) as User
  user.boxToken = await SecretUtils.encryptToken(JSON.stringify(token))
  const resInsert = await insert(db, user)
  return resInsert
}

export function getAuth(tokenStorage?: TokenStorage) {
  return new OAuth({
    config: {
      clientId: config.box.clientId as string,
      clientSecret: config.box.clientSecret as string,
      tokenStorage
    }
  })
}

export function getClient(db: MainDB, user: string) {
  const auth = getAuth(new WfmTokenStorage(db, user))
  return new Client({ auth })
}

export async function getToken(db: MainDB, userId: string): Promise<AccessToken | 'NO_TOKEN_YET'> {
  const user = await get(db, userId) as User
  let token: AccessToken | 'NO_TOKEN_YET'
  if (user.boxToken) {
    token = JSON.parse(await SecretUtils.decryptToken(user.boxToken))
  } else {
    token = 'NO_TOKEN_YET'
  }
  return token
}


const main = async () => {
  const userId = '************'
  const { dbs: { main } } = initDBConnectionSync()
  const client = getClient(main, userId)
  await client.auth.refreshToken()
}
main()
```

### Steps to Reproduce

1. Run an OAuth flow placing the AccessToken in a DB
2. Create a client using an OAuth authentication and an implementation of TokenStorage able to retrieve the AccessToken from the DB for the given user
3. Run any call to an api (works fine if the token was just refresh by the old sdk)
4. Try to refresh the token, and see error below

I actually tried with an expired access token token and it fails at step 3, then I did any call using the legacy box-node-sdk with the exact same AccessToken, and it did refresh it (proving that the refresh token is valid). Then when I rerun the step above, step 3 works, step 4 fails.

If the AccessToken I have at the time I run this is expired, it fails on step 3 trying to do the auto refresh.

### Expected Behavior

The refresh of the token should work

### Error Message, Including Stack Trace

See error above

### Versions Used

Typescript SDK: 0.1.2
Platform: node 18

[sdk-docs]: https://github.com/box/box-ts-sdk-generated/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-ts-sdk-generated/search?type=Issues

**Comment by arjankowski** [comment]
Hi @gdelory,

Thank you for bringing this error here.

In the meantime, I've tried to reproduce it in various ways on my end. 
For instance, I created a custom TokenStorage that operates asynchronously, in which I stored the token obtained by the old `box-node-sdk`. However, despite my efforts, I wasn't able to reproduce the error.

Interestingly, when we refresh the token using the particular `refreshToken`, obtaining a new `AccessToken`, and then use the same already-used `refreshToken` for refreshing, the API returns the same `AccessToken` as previously but with a changed `expiresIn` value.

Therefore, I have a suspicion that storing and retrieving in `WfmTokenStorage` may be causing the `refreshToken` to become corrupted in this SDK. To finally confirm this, I'd like to ask you for one more test. 
Could you please check if the value of the `refreshToken` before storing it in `WfmTokenStorage` using the legacy `box-node-sdk` is the same when using the `box-typescript-sdk-gen`?

To do that, please add this line:
`console.log((await client.auth.tokenStorage.get()).refreshToken)` before this `await client.auth.refreshToken()` and compare the returned value with the one before saving it in WfmTokenStorage.

**Comment by arjankowski** [comment]
I see one more possibility that indicates the `accessToken` is working while the `refreshToken` is not. 
This could also be due to the fact that in both applications, you are using different `clientId` and `clientSecret`. 

This happens because the `accessToken` doesn't require `clientId` and `clientSecret` for its proper functioning, whereas the `refreshToken` works in conjunction with these parameters.

**Comment by gdelory** [comment]
@arjankowski That was it, my local environment was using clientId/secret from another environment... I'm so sorry for wasting your time. Thanks so much for pointing this out to me though, it would take me a while to find out.

Everything works fine, here are the logs showing that the client does refresh automatically and stores correctly the new token in the TokenStorage:

With this 5 lines:
```
  const client = getClient(main, '**********')
  console.log('folderItems')
  console.log(await client.folders.getFolderItems('0'))
  console.log('refresh:')
  console.log(await client.auth.refreshToken())
```

```
folderItems
>>>>>>>> await client.folders.getFolderItems('0') happening here
Trying to read token stored for **********
2023-09-20T17:08:21.930Z utils/DBUtilsServer get: **********
{
  accessToken: '06****************************dR',
  refreshToken: 'qvwnnQG07ZQmip2b****************************EOARTqyRrJs9t2QeCA8K',
  accessTokenTTLMS: 4017000,
  acquiredAtMS: 1695221561923
}
Trying to read token stored for **********
2023-09-20T17:08:23.075Z utils/DBUtilsServer get: **********
{
  accessToken: '06****************************dR',
  refreshToken: 'qvwnnQG07ZQmip2b****************************EOARTqyRrJs9t2QeCA8K',
  accessTokenTTLMS: 4017000,
  acquiredAtMS: 1695221561923
}
>>>>>>>> We got refreshed token automatically
Trying to write the following token to tokenStore: {
  accessToken: '0Q****************************re',
  expiresIn: 4033,
  tokenType: 'bearer',
  restrictedTo: [],
  refreshToken: 'QO4vQsiQLA53WUx76t****************************OaseQ7AtqHicREEE75',
  issuedTokenType: undefined
}
adding box token {"accessToken":"0Q****************************re","expiresIn":4033,"tokenType":"bearer","restrictedTo":[],"refreshToken":"QO4vQsiQLA53WUx76t****************************OaseQ7AtqHicREEE75"} to user
resInsert {"ok":true,"id":"**********","rev":"1467-4a5ee82de34d5c310d1629d55c171b00"}
Trying to read token stored for **********
2023-09-20T17:08:24.550Z utils/DBUtilsServer get: **********
{
  accessToken: '0Q****************************re',
  expiresIn: 4033,
  tokenType: 'bearer',
  restrictedTo: [],
  refreshToken: 'QO4vQsiQLA53WUx76t****************************OaseQ7AtqHicREEE75'
}
{
  totalCount: 22,
  limit: 100,
  offset: 0,
  order: [
    { by: 'type', direction: 'ASC' },
    { by: 'name', direction: 'ASC' }
  ],
  entries: [
    {
      name: '1000files',
      sequenceId: '0',
      id: '23553246939',
      etag: '0',
      type: 'folder'
    },
    ...
  ]
}
refresh:
>>>>>>>> await client.auth.refreshToken() happening here
Trying to read token stored for **********
2023-09-20T17:08:25.423Z utils/DBUtilsServer get: **********
{
  accessToken: '0Q****************************re',
  expiresIn: 4033,
  tokenType: 'bearer',
  restrictedTo: [],
  refreshToken: 'QO4vQsiQLA53WUx76t****************************OaseQ7AtqHicREEE75'
}
Trying to write the following token to tokenStore: {
  accessToken: 'ha****************************ul',
  expiresIn: 4208,
  tokenType: 'bearer',
  restrictedTo: [],
  refreshToken: 'FOnBuH3srHh8WvaOib****************************vVBVckxvENonJV1sMO',
  issuedTokenType: undefined
}
adding box token {"accessToken":"ha****************************ul","expiresIn":4208,"tokenType":"bearer","restrictedTo":[],"refreshToken":"FOnBuH3srHh8WvaOib****************************vVBVckxvENonJV1sMO"} to user
resInsert{"ok":true,"id":"**********","rev":"1468-02cf7e1d5dace03af7c6f72a6b1a21fc"}
{
  accessToken: 'ha****************************ul',
  expiresIn: 4208,
  tokenType: 'bearer',
  restrictedTo: [],
  refreshToken: 'FOnBuH3srHh8WvaOiba****************************VBVckxvENonJV1sMO',
  issuedTokenType: undefined
}
```

I'm closing this ticket since it's a user's mistake. Thanks again for your help!
