### ISSUE TITLE
Help Needed: Configuring Box Storage  OAuth 2.0 Authentication for Access Tokens in PCF Control

### ISSUE THREAD

**Issue by AleehaMaher** [box/box-typescript-sdk-gen#352]
Could someone please guide me on how to configure OAuth authentication for access tokens? I'm working with PCF Control and having trouble setting up OAuth 2.0 authentication.

**Comment by lukaszsocha2** [comment]
Hi @AleehaMaher,
first, you need to set up your app correctly. You can use this guide: https://developer.box.com/guides/authentication/oauth2/oauth2-setup/. Then, you should follow the instructions from this doc: https://github.com/box/box-typescript-sdk-gen/blob/main/docs/authentication.md#oauth-20-auth. It shows how to use OAuth 2.0 using Typescript SDK. 
In case you have any troubles, let us know.
Best,
@lukaszsocha2
