### ISSUE TITLE
Failed to execute 'fetch' on 'Window': The `duplex` member must be specified for a request with a streaming body

### ISSUE THREAD

**Issue by gamenic-manjul** [box/box-typescript-sdk-gen#417]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Error is occurred while calling uploadFilePart
https://github.com/box/box-typescript-sdk-gen/blob/main/docs/chunkedUploads.md#upload-part-of-file

This is what i am doing

const chunkBuffer = await file.slice(start, end).arrayBuffer()
const wordArray = CryptoJS.enc.Latin1.parse(chunkBuffer)
const digest = `sha=${CryptoJS.SHA1(wordArray).toString(CryptoJS.enc.Base64)}`
const contentRange = `bytes ${start}-${end - 1}/${totalSize}`

await client.chunkedUploads.uploadFilePart(
  sessionId,
  generateByteStreamFromBuffer(chunkBuffer),
  {
    digest: digest,
    contentRange: contentRange,
  } satisfies UploadFilePartHeadersInput,
);

This gives error saying:
ERROR TypeError: Failed to execute 'fetch' on 'Window': The `duplex` member must be specified for a request with a streaming body
    at box-typescript-sdk-gen.js?v=0cfea8e7:1722:57
    at Generator.next (<anonymous>)
    at fulfilled (box-typescript-sdk-gen.js?v=0cfea8e7:1616:28)

### Steps to Reproduce
I have written code above

### Expected Behavior

It should send request

### Error Message, Including Stack Trace

ERROR TypeError: Failed to execute 'fetch' on 'Window': The `duplex` member must be specified for a request with a streaming body
    at box-typescript-sdk-gen.js?v=0cfea8e7:1722:57
    at Generator.next (<anonymous>)
    at fulfilled (box-typescript-sdk-gen.js?v=0cfea8e7:1616:28)

### Screenshots

<img width="991" alt="Screenshot 2024-11-17 at 13 43 32" src="https://github.com/user-attachments/assets/6addb80e-81ce-48d5-9441-7a65f72a3fb1">

### Versions Used

Typescript SDK: 1.7.0
Platform: Vue3 + TypeScript (Browser)
Node.js (if applicable): 20.10.0

**Comment by mwwoda** [comment]
Hi @gamenic-manjul 

Looks like on some browser we need to set additional parameter to fetch called `duplex`. https://developer.chrome.com/docs/capabilities/web-apis/fetch-streaming-requests#half_duplex.

I'll try to submit a fix for this

**Comment by gamenic-manjul** [comment]
Hi @mwwoda 
Thank you for the response.

How much time could it take to push the fix?

Its a bit urgent, if it takes time, is there any workaround for now?

**Comment by mwwoda** [comment]
We currently have a PR in our codegen repo (from which this SDK is builtin). When it's merged the change will be propagated to this repo.

You can apply this change locally by adding :
`...(fileStream && isBrowser() && { duplex: 'half' }),`
to the returned value here
https://github.com/box/box-typescript-sdk-gen/blob/main/src/networking/fetch.ts#L190-L209

**Comment by mwwoda** [comment]
should be fixed by https://github.com/box/box-typescript-sdk-gen/pull/420

**Comment by mwwoda** [comment]
Will be released with the next SDK version

**Comment by gamenic-manjul** [comment]
Thank you so much

**Comment by congminh1254** [comment]
Hi @gamenic-manjul 

We have just released the new version of the Box TS SDK, including this fix and some improvement for the [Upload Big File](https://github.com/box/box-typescript-sdk-gen/blob/main/docs/chunkedUploads.md#upload-big-file) function.

Please take a look.
