### ISSUE TITLE
How to set a global request timeout

### ISSUE THREAD

**Issue by drinksbydrew** [box/box-typescript-sdk-gen#448]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

I'm having a request hang indefinitely. I haven't figured out which one yet. Is there a way to set a global request timeout? I saw a `networkSession` parameter to the BoxClient constructor but I'm not sure that that's the right thing to use.

I saw in other libraries, like the box-java-library, that there is a way to configure a timeout. I just can't seem to find that for this library.

### Versions Used

Typescript SDK: 1.6.0 (box-typescript-sdk-gen)
Platform: node
Node.js (if applicable): 20.12

[sdk-docs]: https://github.com/box/box-typescript-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-typescript-sdk-gen/search?type=Issues

**Comment by congminh1254** [comment]
Hi @drinksbydrew 
Currently we don't have any global configuration of the timeout for the fetch request, but we are providing the `cancellationToken` is an instance of `AbortSignal`.

So to cancel a request after 5 seconds, you can do something like:
```
const signal = AbortSignal.timeout(5000);
await boxClient.users.getUserMe(undefined, undefined, signal);
```
