### ISSUE TITLE
Client Credentials Grant (CCG) issue related to tokenStorage

### ISSUE THREAD

**Issue by buraian** [box/box-typescript-sdk-gen#53]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

I am using v0.2.0 trying to authenticate with CCG but am receiving a console error at ccgAuth.js:49:1. Error is thrown when `getFolderItems` is called.

When I tested with a developer token it worked fine. Please help!

Here is my code and is configured per the docs:

```ts
import { BoxClient } from 'box-typescript-sdk-gen/lib/client.generated';
import { BoxCcgAuth } from 'box-typescript-sdk-gen/lib/ccgAuth.js';

const ccgConfig = {
  enterpriseId: 'XXXXXX',
  clientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  clientSecret: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
};
const auth = new BoxCcgAuth({ config: ccgConfig });
const client = new BoxClient({ auth: auth });

export const getFolderItems = async (folderId: string) => {
  const result = await client.folders.getFolderItems(folderId);

  return result;
}
```

### Error Message, Including Stack Trace

Here is the console error:

```
TypeError: Cannot read properties of undefined (reading 'get')
    at BoxCcgAuth.<anonymous> (ccgAuth.js:49:1)
    at Generator.next (<anonymous>)
    at ccgAuth.js:8:1
    at new Promise (<anonymous>)
    at A4av.__awaiter (ccgAuth.js:4:1)
    at BoxCcgAuth.retrieveToken (ccgAuth.js:48:1)
    at fetch.js:74:42
    at Generator.next (<anonymous>)
    at fulfilled (fetch.js:5:42)
```

Here is the line in ccgAuth that throws the error:

```
const token = yield this.tokenStorage.get();
```

The tokenStorage value in the auth object appears to be undefined (see screenshot). Possibly the issue?

### Screenshots

<img width="841" alt="Screenshot 2024-02-01 at 5 44 59 PM" src="https://github.com/box/box-typescript-sdk-gen/assets/7258147/caac779b-9705-4450-8daf-e00b06cb2a8a">

### Versions Used

Typescript SDK: 0.2.0
Platform: Chrome Browser

[sdk-docs]: https://github.com/box/box-typescript-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-typescript-sdk-gen/search?type=Issues

**Comment by mwwoda** [comment]
Hello,
It looks like constructor of CcgConfig takes care of creation of the default token storage (InMemoryTokenStorage). Try using the constructor when creating CcgConfig
So replace

```ts
const ccgConfig = {
  enterpriseId: 'XXXXXX',
  clientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  clientSecret: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
};
```

with

```ts
const ccgConfig = new CcgConfig({
  enterpriseId: 'XXXXXX',
  clientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  clientSecret: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
});
```

also don't forget about the import
```ts
import { BoxCcgAuth, CcgConfig } from 'box-typescript-sdk-gen/lib/ccgAuth.js';
```

**Comment by buraian** [comment]
This fixed the error. Thank you @mwwoda !
