### ISSUE TITLE
event.getEvents throws error: Can't deserialize EventSourceOrFileOrFolderOrUser undefined

### ISSUE THREAD

**Issue by nk-va** [box/box-typescript-sdk-gen#56]
- [ x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ x I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

`client.events.getEvents` returns the following error:

`Can't deserialize EventSourceOrFileOrFolderOrUser`

### Steps to Reproduce

Execute the following code in node (with correctly initialized box client):

```js
const events = await client.events.getEvents()

// Throws an error:
Can't deserialize EventSourceOrFileOrFolderOrUser undefined
```

However, using a direct request by first getting the auth token and using fetch returns expected json:

```js
const token = await client.events.auth?.retrieveToken()

const response = await fetch(`https://app.box.com/2.0/events`, {
  headers: {
    Authorization: `Bearer ${token?.accessToken}`,
  },
})

console.log(response.json())
// events {
//  entries: [
//    {
//      type: 'event',
// ...
```

### Expected Behavior

I expect getEvents to return a json object similar to the fetch call.

### Error Message, Including Stack Trace

Full error:

```
Error: Can't deserialize EventSourceOrFileOrFolderOrUser
    at deserializeEventSourceOrFileOrFolderOrUser (/app/node_modules/box-typescript-sdk-gen/lib/schemas.generated.js:9070:11)
    at deserializeEvent (/app/node_modules/box-typescript-sdk-gen/lib/schemas.generated.js:9523:11)
    at /app/node_modules/box-typescript-sdk-gen/lib/schemas.generated.js:9559:24
    at Array.map (<anonymous>)
    at deserializeEvents (/app/node_modules/box-typescript-sdk-gen/lib/schemas.generated.js:9558:27)
    at EventsManager.<anonymous> (/app/node_modules/box-typescript-sdk-gen/lib/managers/events.generated.js:61:65)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/box-typescript-sdk-gen/lib/managers/events.generated.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Screenshots

None

### Versions Used

Typescript SDK: 0.3.0
Platform: node
Node.js (if applicable): 20

[sdk-docs]: https://github.com/box/box-typescript-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-typescript-sdk-gen/search?type=Issues

**Comment by arjankowski** [comment]
Hi @nk-va , thanks for reporting the issue.
The problem stems from the specific data format in response to the `getEvents` endpoint, and we'll address it soon. 
Once we fix it, we'll notify you here

Regards,
Artur

**Comment by congminh1254** [comment]
Hi @nk-va 
We have just release version 0.5.4 of Typescript SDK and the issue above should be fixed.
Please download the latest version and let us know if it's working now.
Best regards,
Minh
