### ISSUE TITLE
Use built-in `FormData` instead of `form-data` library

### ISSUE THREAD

**Issue by michaelhays** [box/box-typescript-sdk-gen#96]
Hey there, I'm trying to upload a file with `client.uploads.uploadFile()`, and am seeing the error:

```
Cannot find module 'form-data'
```

The error happens when calling `eval('require')('form-data')` [here](https://github.com/box/box-typescript-sdk-gen/blob/14e115481c778614439a76eafc57a24edb5da714/src/networking/fetch.ts#L133).

This is the same issue that I ran into with #54, so it seems that the `eval('require')('<library>')` approach still breaks with my configuration for some reason, whether that's due to Vercel, ESM vs CJS, or something else. (Note that I tried installing `form-data` to my `package.json`, to no avail.)

It's probably wise to figure out what is going on at the root here, but I think a good immediate solution would be to drop the `form-data` library in favor of just using the [`FormData`](https://nodejs.org/docs/latest-v18.x/api/globals.html#class-formdata) that has been built-in to Node.js since v18.

This would require dropping support for Node.js 16, but that has been [end-of-life since September 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol), so this seems like a reasonable time to do so. Plus, Node.js 16 could still work with the [`--experimental-fetch` flag](https://nodejs.org/docs/latest-v16.x/api/cli.html#--experimental-fetch).

There are some other good reasons to drop `form-data` laid out in this issue: https://github.com/form-data/form-data/issues/537

What do you think?

**Comment by lukaszsocha2** [comment]
Hi @michaelhays,
thanks for reaching us. Let me talk about this one with the team and we'll get back to you.
Best,
@lukaszsocha2

**Comment by mhagmajer** [comment]
Thanks! We are going to plan doing this.

**Comment by mhagmajer** [comment]
Hi @michaelhays, we're already using `FormData` in browser environment https://github.com/box/box-typescript-sdk-gen/blob/d86a9b3978f1044a3cb28a7243aaa923696343fa/src/networking/fetch.ts#L132. Please feel free to reopen the issue as needed. Thanks for reaching out!

**Comment by michaelhays** [comment]
Hi @mhagmajer, the problem on my end is actually the very next line:

https://github.com/box/box-typescript-sdk-gen/blob/d86a9b3978f1044a3cb28a7243aaa923696343fa/src/networking/fetch.ts#L133

The `eval('require')` approach doesn't work in a Vercel environment, as discussed in #54. That PR was fixed by simply removing the library, which wasn't necessary. In this case, you can do the same thing, since the `form-data` library is no longer needed as of Node.js 18, since `FormData` is now built in with Node.

Could you please re-open this issue? The only way I'm able to use this library right now is by patching it to remove the call to `eval('require')('form-data')`.

**Comment by michaelhays** [comment]
You can keep this closed in favor of #213, since I finally figured out the root issue.
